"""create_initial_tables

Revision ID: b33d7ccb841b
Revises: 
Create Date: 2026-06-14 18:48:28.788673

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33d7ccb841b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('benchmark_slug', sa.String(length=128), nullable=False),
    sa.Column('run_label', sa.String(length=512), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('harness_version', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('global_score', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('raw_artifact_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_benchmark_slug'), ['benchmark_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_job_id'), ['job_id'], unique=True)

    op.create_table('run_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('benchmark_task_id', sa.String(length=255), nullable=True),
    sa.Column('task_slug', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raw_task_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_tasks_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_tasks_task_slug'), ['task_slug'], unique=False)

    op.create_table('failure_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_task_id', sa.String(length=36), nullable=False),
    sa.Column('is_failure', sa.Boolean(), nullable=False),
    sa.Column('taxonomy_primary', sa.String(length=64), nullable=True),
    sa.Column('taxonomy_secondary', sa.String(length=64), nullable=True),
    sa.Column('diagnosis_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_task_id'], ['run_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failure_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failure_labels_run_task_id'), ['run_task_id'], unique=True)

    op.create_table('trace_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_task_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_task_id'], ['run_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trace_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_steps_run_task_id'), ['run_task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_steps_run_task_id'))

    op.drop_table('trace_steps')
    with op.batch_alter_table('failure_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failure_labels_run_task_id'))

    op.drop_table('failure_labels')
    with op.batch_alter_table('run_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_tasks_task_slug'))
        batch_op.drop_index(batch_op.f('ix_run_tasks_run_id'))

    op.drop_table('run_tasks')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_runs_benchmark_slug'))

    op.drop_table('runs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
